export interface Iinfo{
    id: number,
    nazwa: string,
    nazwaen: string,
    nazwade: string,
    naglowek: string,
    tekst:string,
    g:number,
    parent:number,
    nr:number,
    widocznosci:number,
    widocznosc_linku:number,
    nazwa_pliku:string,
    nazwa_plikuen:string,
    nazwa_llikude:string,
    link:string,
    szablon:string,
    img:string,
    img_strona:string,
    title:string,
    description:string,
    keywords:string,
    artykuly_id:number,
    dodatkowe_id:number,
    grupy_sekcyjne_id:number,
    banery_id:number
}